package us.lsi.dp1.newcorporder.match;

public enum MatchTurnState {

    SELECTING_ACTION,

    // PLOT
    SELECTING_FIRST_SHARE,
    SELECTING_SECOND_SHARE,
    REMOVING_SHARES_FROM_HAND,

    //TAKE OVER
    SELECTING_CONSULTANT,
    ROTATING_CARDS,
    CHOOSING_COMPANY_TAKEOVER,
    ACTIVATING_COMPANY_ABILITY,

    //COMPANY ABILITIES
    SELECTING_COMPANIES_FOR_BROADCAST_NETWORK_ABILITY,
    SELECTING_CONGLOMERATES_FOR_PRINT_MEDIA_ABILITY,
    SELECTING_CONGLOMERATES_FOR_GUERRILLA_MARKETING_ABILITY,
    SELECTING_CONGLOMERATES_FOR_AMBIENT_ADVERTISING_ABILITY,
    SELECTING_COMPANIES_FOR_ONLINE_MARKETING_ABILITY,
    SELECTING_CONGLOMERATE_FOR_SOCIAL_MEDIA_ABILITY,

}
